name: Daily Commit Automation

on:
  schedule:
    # Runs every day at 04:30 UTC (set specific time here)
    - cron: '30 4 * * *'
  workflow_dispatch:  # Optional: allows you to manually trigger it for testing

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Commit and push changes (23f3004489@ds.study.iitm.ac.in)
        run: |
          echo "Daily update: $(date -u)" >> daily-update.log
          git config user.name "github-actions"
          git config user.email "23f3004489@ds.study.iitm.ac.in"
          git add daily-update.log
          git commit -m "Automated daily commit - $(date -u)" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
